# Generated by Django 3.0.2 on 2020-01-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='object creation time', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='object modification time', verbose_name='modified')),
                ('username', models.CharField(help_text='username for this user', max_length=128, unique=True, verbose_name='username')),
                ('first_name', models.CharField(help_text='first name for this user', max_length=128, verbose_name='first name')),
                ('last_name', models.CharField(help_text='last name for this user', max_length=128, verbose_name='last name')),
                ('email', models.EmailField(blank=True, help_text='email for this user', max_length=254, verbose_name='email')),
                ('iban', models.CharField(help_text='iban for this user', max_length=128, verbose_name='iban')),
                ('role', models.CharField(choices=[('BUILDING_MANAGER', 'Building manager'), ('BUILDING_RESIDENT', 'Building resident')], help_text='role for this user', max_length=32, verbose_name='role')),
                ('is_admin', models.BooleanField(default=False, help_text='is this user admin?', verbose_name='is admin')),
                ('is_active', models.BooleanField(default=True, help_text='is this user active?', verbose_name='is active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
